### ISSUE TITLE
Build is not working on Python3.6 environment

### ISSUE THREAD

**Issue by anupamgovind1981** [rigglemania/pysqlcipher3#15]
python3 setup.py build
running build
running build_py
running build_ext
Builds a C extension linking against libsqlcipher library
building 'pysqlcipher3._sqlite3' extension
gcc -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -Qunused-arguments -DMODULE_NAME="pysqlcipher3.dbapi2" -I/Users/agovind/anaconda3/include/python3.6m -c src/python3/module.c -o build/temp.macosx-10.7-x86_64-3.6/src/python3/module.o
In file included from src/python3/module.c:24:
src/python3/connection.h:33:10: fatal error: 'sqlcipher/sqlite3.h' file not found
#include "sqlcipher/sqlite3.h"
         ^~~~~~~~~~~~~~~~~~~~~
1 error generated.
error: command 'gcc' failed with exit status 1

**Comment by lucaruzzola** [comment]
I am getting the same error on Ubuntu 16.04 with python3.5. I installed SQLCipher using sudo apt-get install sqlcipher. Did you solve this?

**Comment by VijayalakshmiSundaravaradhan** [comment]
Install sqlcipher dev package
sudo apt-get install libsqlcipher-dev

**Comment by Falmarri** [comment]
This was caused by this commit https://github.com/rigglemania/pysqlcipher3/commit/6ca3743085924c7b97d54af7e5594d08ad60d343 I don't understand what the commit message is saying, or why this is correct. But having the files in /usr/include/sqlcipher isn't standard, and this also breaks the amalgamation version, because the amalgamation version does an `-Iamalgamation`, but it checks for the sqlite3.c file being in there

**Comment by dreamflasher** [comment]
> 
> 
> Install sqlcipher dev package
> sudo apt-get install libsqlcipher-dev

Thank you! This took me quite a while to figure out.
